import type { Metadata } from "next";
import Image from "next/image";
import "../globals.css";
import ThemeRegistry from "@/components/ThemeRegistry";
import { Box } from '@mui/material'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <>
      <ThemeRegistry>
        <Box sx={ { display: 'flex' } }>
          <Image
            src="/Left.png"
            width={ 700 }
            height={ 870 }
            alt="Left side Image"
            style={ { height: '100%' } }
          />
          <div className="w-full md:w-1/2 flex items-center justify-center p-8 ">
            { children }
          </div>


        </Box>


      </ThemeRegistry >
    </>
  );
}
